// Draws the chapter cover art and the social preview from code, so no source images are ever committed.
// Run with: node scripts/make-images.mjs
import { mkdirSync, writeFileSync } from 'node:fs'
import sharp from 'sharp'

const OUT = 'public/img'
const WIDTHS = [320, 640, 960]
const HUES = [215, 165, 265, 190, 285, 140, 235]
const CHAPTERS = HUES.length

/** A small deterministic random source, so every run draws the same art. */
function seeded(seed) {
  let state = seed * 9301 + 49297
  return () => {
    state = (state * 9301 + 49297) % 233280
    return state / 233280
  }
}

function coverSvg(index) {
  const hue = HUES[index - 1]
  const random = seeded(index * 7)
  const width = 960
  const height = 360
  const bars = 40
  const gap = width / bars
  let level = 0.5
  const rects = Array.from({ length: bars }, (_, i) => {
    level = Math.min(0.95, Math.max(0.12, level + (random() - 0.5) * 0.45))
    const h = Math.round(level * 250)
    const x = Math.round(i * gap + 6)
    return `<rect x="${x}" y="${height - 46 - h}" width="${Math.round(gap - 12)}" height="${h}" rx="6" fill="hsl(${hue + 20} 75% 78%)" opacity="0.9"/>`
  }).join('')
  const holes = Array.from({ length: 24 }, (_, i) => `<circle cx="${20 + i * 40}" cy="${height - 14}" r="7" fill="hsl(${hue} 40% 96%)"/>`).join('')
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="hsl(${hue} 55% 20%)"/><stop offset="1" stop-color="hsl(${hue + 35} 60% 34%)"/></linearGradient></defs>
<rect width="${width}" height="${height}" fill="url(#g)"/>
<circle cx="${820 - index * 30}" cy="80" r="46" fill="hsl(${hue + 50} 80% 85%)" opacity="0.35"/>
${rects}${holes}
</svg>`
}

function ogSvg() {
  const lines = Array.from({ length: 7 }, (_, i) => `<rect x="120" y="${250 + i * 38}" width="${560 - ((i * 53) % 190)}" height="12" rx="6" fill="#9aa9c2" opacity="0.7"/><rect x="${900 - ((i * 37) % 60)}" y="${250 + i * 38}" width="${60 + ((i * 37) % 60)}" height="12" rx="6" fill="#7cc8a3"/>`).join('')
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
<rect width="1200" height="630" fill="#eef4fb"/>
<rect x="80" y="50" width="1040" height="530" rx="18" fill="#ffffff" stroke="#c9d7ea" stroke-width="3"/>
<text x="120" y="150" font-family="Arial, Helvetica, sans-serif" font-size="70" font-weight="700" fill="#13202f">Your Life, In Receipts</text>
<text x="120" y="205" font-family="Arial, Helvetica, sans-serif" font-size="30" fill="#4a5b70">Music, household spending and card receipts, told as a story</text>
${lines}
</svg>`
}

mkdirSync(OUT, { recursive: true })
for (let index = 1; index <= CHAPTERS; index += 1) {
  const svg = Buffer.from(coverSvg(index))
  for (const width of WIDTHS)
    await sharp(svg).resize({ width }).webp({ quality: 62, effort: 6 }).toFile(`${OUT}/chapter-${index}-${width}.webp`)
}
await sharp(Buffer.from(ogSvg())).png({ palette: true, colors: 32, compressionLevel: 9 }).toFile(`${OUT}/og.png`)
writeFileSync(`${OUT}/README.txt`, 'Generated by scripts/make-images.mjs. Do not edit by hand.\n')
console.log('IMAGES-OK')
